spacing = 1
padding = 0
hide_ascii = false 
separator = "*"
separator_color = "#CBA6F7"
key_color = "#94E2D5"

[palette]
glyph = " "
visible = false
type = "Dark"

[bar]
visible = false
glyph = "󰨐"
symbol_open = '['
symbol_close = ']'
hide_delimiters = false 

[box]
title = ""
border = "plain"
visible = true

[custom_ascii]
color = "#ffffff"
path = "~/.config/macchina/themes/ascii"

# [keys]
# de = "UI"
