use = [
    "./theme.toml",
]

[general]
font = "JetBrainsMono Nerd Font"
anchor = "right"
offset = [10, 15]
width = 84
height = 84
gap = 10
limit = 10
idle_threshold = "10s"
sorting = "urgency"

[display]
markup = true
padding = [5, 10] 
theme = "main"
layout = "./layout.noti"

[display.icons]
theme = "Breeze-dark"
size = [64]

[display.timeout]
default = 0

[display.image]
max_size = 74
margin = { right = 0 }
rounding = 0

[display.border]
size = 0
radius = 10

[display.text]
alignment = "left"
wrap = false
ellipsize = "end" 

[display.title]
font_size = 20
style = "bold"

[display.body]
justify = true
font_size = 14
