[general]
anchor = "top"
offset = [0, 0]
font = ["Gotham", 16]
width = 300
height = 100
gap = 10
sorting = "default"

[display]
markup = true
padding = { horizontal = 0 }
timeout = 0

[display.image]
max_size = 128
margin = 0
rounding = 0

[display.border]
size = 15
color = "#333"
radius = 0

[display.colors]
low = { background = "#30303030", foreground = "#fff" }
normal = { background = "#151523", foreground = "#fff" }
critical = { background = "#FF0000", foreground = "#fff" }

[display.text]
justification = "left"
margin = { left = 15 }
wrap = false
ellipsize_at = "middle" 

[display.title]
style = "bold"

# NOTE: #ff0000
[[app]]
name = "red-border"

[app.display]
border = { color = "#ff0000" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "red-border-semitransparent"

[app.display]
border = { color = "#ff000050" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "red-border-transparent"

[app.display]
border = { color = "#ff000000" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #00ff00
[[app]]
name = "green-border"

[app.display]
border = { color = "#00ff00" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "green-border-semitransparent"

[app.display]
border = { color = "#00ff0050" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "green-border-transparent"

[app.display]
border = { color = "#00ff0000" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #0000ff
[[app]]
name = "blue-border"

[app.display]
border = { color = "#0000ff" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "blue-border-semitransparent"

[app.display]
border = { color = "#0000ff50" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "blue-border-transparent"

[app.display]
border = { color = "#0000ff00" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #000000
[[app]]
name = "black-border"

[app.display]
border = { color = "#000000" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#ff0000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "black-border-semitransparent"

[app.display]
border = { color = "#00000050" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#ff0000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "black-border-transparent"

[app.display]
border = { color = "#00000000" }

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#ff0000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #ffffff
[[app]]
name = "white-border"

[app.display]
border = { color = "#ffffff" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "white-border-semitransparent"

[app.display]
border = { color = "#ffffff50" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "white-border-transparent"

[app.display]
border = { color = "#ffffff00" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #c8c8c8
[[app]]
name = "gray-border"

[app.display]
border = { color = "#c8c8c8" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#ff0000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "gray-border-semitransparent"
[app.display]
border = { color = "#c8c8c850" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#ff0000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "gray-border-transparent"
[app.display]
border = { color = "#c8c8c800" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#ff0000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #ff00cc
[[app]]
name = "pink-border"

[app.display]
border = { color = "#ff00cc" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "pink-border-semitransparent"
[app.display]
border = { color = "#ff00cc50" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "pink-border-transparent"
[app.display]
border = { color = "#ff00cc00" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

# NOTE: #fff600
[[app]]
name = "yellow-border"

[app.display]
border = { color = "#fff600" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "yellow-border-semitransparent"
[app.display]
border = { color = "#fff60050" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"

[[app]]
name = "yellow-border-transparent"
[app.display]
border = { color = "#fff60000" } 

[app.display.colors.low]
background = "#ffffff"
foreground = "#151523"

[app.display.colors.normal]
background = "#000000"
foreground = "#ffffff"

[app.display.colors.critical]
background = "#c8c8c8"
foreground = "#000000"
