[general]
font = [ "JetBrainsMono Nerd Font", 20 ]
anchor = "top right"
offset = [10, 20]
width = 400
height = 90
gap = 10
sorting = "default"

[display]
markup = true
padding = { horizontal = 32, vertical = 5 }
timeout = 5000
ellipsize_at = "middle" 
alignment = "left"

[display.image]
max_size = 64
margin = 0

[display.border]
size = 2
color = "#CDD6F430"
radius = 10

[display.colors]
low = { background = "#151523", foreground = "#CDD6F4" }
normal = { background = "#1e1e2e", foreground = "#CDD6F4" }
critical = { background = "#f38ba8", foreground = "#cdd6f4" }

[display.title]
justification = "left"
alignment = "left"
margin = { left = 20 }
wrap = false
style = "bold"

[display.body]
alignment = "left"
justification = "left"
margin = { left = 20 }
wrap = false
