[general]
font = [ "JetBrainsMono Nerd Font", 16 ]
anchor = "bottom right"
offset = [10, 20]
width = 250
height = 60
gap = 8
sorting = "default"

[display]
markup = true
padding = { horizontal = 32 }
timeout = 3000 

[display.image]
max_size = 32
margin = 0

[display.border]
size = 2
color = "#6B729A"
radius = 50

[display.colors]
low = { background = "#151523", foreground = "#CDD6F4" }
normal = { background = "#1e1e2e", foreground = "#CDD6F4" }
critical = { background = "#f38ba8", foreground = "#151523" }

[display.text]
justification = "left"
margin = { left = 15 }
wrap = false
ellipsize_at = "middle" 

[display.title]
style = "bold"
