use = [
    "./themes/main.toml",
    "./apps/*",
]

[general]
font = "JetBrainsMono Nerd Font"
anchor = "top right"
offset = [15, 15]
width = 330
height = 80
gap = 8
limit = 10
idle_threshold = "10s"

[general.sorting]
by = "urgency"
ordering = "ascending"

[display]
markup = true
padding = { horizontal = 20, vertical = 5 }
theme = "main"
# layout = "./layouts/layout.noti"

[display.icons]
theme = "Breeze"

[display.timeout]
default = 5000
critical = 0

[display.image]
max_size = 32
margin = { right = 15 }
rounding = 0

[display.border]
size = 1
radius = 0

[display.text]
font_size = 14
alignment = "left"
justify = true
ellipsize = "end"
wrap = false

[display.summary]
style = "bold"

[display.body]
font_size = 12
