[general]
font = [ "JetBrainsMono Nerd Font", 20 ]
anchor = "bottom right"
offset = [10, 20]
width = 300
height = 80
gap = 5
sorting = "default"

[display]
markup = true
padding = { horizontal = 32 }
timeout = 3000

[display.image]
max_size = 48
margin = 0

[display.border]
size = 2
color = "#9F99CC"
radius = 50

[display.colors]
low = { background = "#151523", foreground = "#CDD6F4" }
normal = { background = "#1e1e2e", foreground = "#CDD6F4" }
critical = { background = "#f38ba8", foreground = "#151523" }

[display.text]
justification = "left"
margin = { left = 20 }
wrap = false
ellipsize_at = "middle" 

[display.title]
style = "bold"
