use = [
    "~/.config/noti/themes/main.toml",
    "~/.config/noti/apps/spotify.toml"
]

[general]
font = "JetBrainsMono Nerd Font"
anchor = "top right"
offset = [10, 15]
width = 300
height = 80
gap = 8
sorting = "urgency"
sound = "/home/hapka/Documents/kits/!Ghosty - floatszn/!fx/!Ghosty - ddt.wav"
limit = 3

[display]
markup = true
padding = { horizontal = 20 }
theme = "main"
# layout = "/home/hapka/.config/noti/layouts/layout.noti"
timeout = 4000

[display.image]
max_size = 38
margin = 0
rounding = 0

[display.border]
size = 2
radius = 12

[display.text]
justification = "left"
margin = { left = 15 }
wrap = false
ellipsize_at = "middle" 
font_size = 18

[display.title]
style = "bold"
