use = [
    "./themes/main.toml",
    "./apps/*",
]

[general]
font = "JetBrainsMono Nerd Font"
anchor = "top right"
offset = [10, 15]
width = 300
height = 80
gap = 8
limit = 10
idle_threshold = "10s"

[general.sorting]
by = "urgency"
ordering = "ascending"

[display]
markup = true
padding = { horizontal = 20, vertical = 5 }
theme = "main"
# layout = "./layouts/layout.noti"

[display.icons]
theme = "Breeze-dark"

[display.timeout]
default = 5000
critical = 0

[display.image]
max_size = 38
margin = { right = 15 }
rounding = 0

[display.border]
size = 2
radius = 12

[display.text]
alignment = "left"
justify = false
margin = 0
font_size = 16
ellipsize = "end"

[display.title]
style = "bold"
wrap = false

[display.body]
font_size = 15
wrap = true
wrap_mode = "word-char"
