[general]
font = [ "JetBrainsMono Nerd Font", 18 ]
anchor = "bottom"
offset = [0, 20]
width = 300
height = 100
gap = 8
sorting = "default"

[display]
markup = true
padding = { horizontal = 20 }
timeout = 5000

[display.image]
max_size = 38
margin = 0
rounding = 0

[display.border]
size = 2
color = "#ABB2BF30"
radius = 10

[display.colors]
low = { background = "#1D1E21", foreground = "#ABB2BF" }
normal = { background = "#1D1E21", foreground = "#ABB2BF" }
critical = { background = "#1D1E21", foreground = "#E06B74" }

[display.text]
justification = "left"
margin = { left = 15 }
wrap = false
ellipsize_at = "middle" 

[display.title]
style = "bold"

[[app]]
name = "Spotify"
[app.display]
padding = { horizontal = 14 }
image = { rounding = 5, max_size = 64 }

[[app]]
name = "YouTube Music"
[app.display]
padding = { horizontal = 14 }
image = { rounding = 5, max_size = 64 }
