[[theme]]
name = "main-spotify"

[theme.low]
background = "#12121890"
foreground = "#ABB2BF"
[theme.low.border]
mode = "linear-gradient"
degree = 180
colors = ["#1ED760", "#ABB2BF"]

[[app]]
name = "Spotify"
[app.display]
theme = "main-spotify"
padding = { horizontal = 10 }
image = { rounding = 1, max_size = 64 }

# [app.display.text]
# font = "BigBlueTermPlus Nerd Font"
