require("core.lsp.servers.clangd")
require("core.lsp.servers.luals")
require("core.lsp.servers.tailwindcss")
require("core.lsp.servers.json")
require("core.lsp.servers.typescript")
require("core.lsp.servers.prisma")
require("core.lsp.servers.rust")
require("core.lsp.servers.other")
