[[theme]]
name = "main"

[theme.low]
background = "#12121890"
foreground = "#ABB2BF"
border = "#4b4b57"

[theme.normal]
background = "#12121890"
foreground = "#ABB2BF"
border = "#676778"

[theme.critical]
background = "#12121890"
foreground = "#ABB2BF"
border = "#E06B74"

