[pyprland]
plugins = [
    "shift_monitors",
    "workspaces_follow_focus",
    "expose",
    "gbar",
    "layout_center",
    "scratchpads",
]

[expose]
include_special = false

[gbar]
monitors = ["eDP-1"]

[scratchpads.spotify]
animation = "fromBottom"
command = "spotify"
class = "Spotify"
position = "0% 3%"
size = "100% 97%"
unfocus = "hide"
lazy = true
