windowrule = float on, match:class org.freedesktop.impl.portal.desktop.kde
windowrule = stay_focused on, match:class ^(Rofi)$
windowrule = no_blur on, match:class firefox-developer-edition
windowrule = no_blur on, match:title Zen Browser
windowrule = no_shadow on, match:title Spotify
windowrule = no_shadow on, match:title Youtube Music
windowrule = immediate on, match:class ^(dota2)$
windowrule = immediate on, match:title Risk of Rain 22

# WORKSPACE RULES
# On created empty
workspace = special:music, on-created-empty:LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify-launcher
# Smart gaps
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]
# windowrule = border_size 0, match:float 0, match:workspace f[1]
# windowrule = rounding 0, match:float 0, match:workspace f[1]

# LAYER RULES
# Blur
layerrule = dim_around on, match:namespace rofi
# eww bar layer
layerrule = blur on, match:namespace bar
layerrule = blur_popups on, match:namespace bar
layerrule = xray on, match:namespace bar
layerrule = ignore_alpha 0, match:namespace bar

# DEV
# drawlab
windowrule = workspace 4 silent, match:class drawlab
# opengl
windowrule = float on, match:title OpenGL
windowrule = size 800 600, match:title OpenGL
windowrule = move 100%-800 30, match:title OpenGL
windowrule = no_focus on, match:title OpenGL
# sfml-chess
windowrule = float on, match:title sfml-chess
windowrule = center on, match:title sfml-chess
windowrule = move 100%-w-0 30, match:title sfml-chess

# noti
layerrule = blur on, match:namespace noti
layerrule = blur_popups on, match:namespace noti
# layerrule = xray on, match:namespace noti
layerrule = ignore_alpha 0, match:namespace noti
layerrule = no_anim on, match:namespace noti

# waybar
layerrule = blur on, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar
layerrule = xray on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = no_anim on, match:namespace waybar
