# Variables
$term = uwsm app -- wezterm start --always-new-process
$menu = uwsm app -- rofi -show drun
$power = $SCRIPTS/rofi-power-menu.sh
$volume = $SCRIPTS/volume.sh
$brightness = $SCRIPTS/brightness.sh
$kb = $SCRIPTS/kb.sh
$gamemode = $SCRIPTS/gamemode.sh
$moveToWorkspaceAndCloseSpecial = $SCRIPTS/moveToWorkspaceAndCloseSpecial.sh
